
project_id = "xcmqjkvyvuhoslbzmlgi"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 900
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.log-security-event]
verify_jwt = true

[functions.export-compliance-report]
verify_jwt = true

[functions.ai-analysis]
verify_jwt = false
# @public-ok - AI analysis can be used publicly

[functions.leads-invite]
verify_jwt = false
# @public-ok - Public invitation system

[functions.events-track]
verify_jwt = false
# @public-ok - Analytics tracking can be public

[functions.advisors-assign]
verify_jwt = true

[functions.plaid-create-link-token]
verify_jwt = true

[functions.plaid-exchange-public-token]
verify_jwt = true

[functions.plaid-sync-accounts]
verify_jwt = true

[functions.process-transfer]
verify_jwt = true

[functions.stripe-ach-transfer]
verify_jwt = true

[functions.stripe-ach-webhook]
verify_jwt = false
# @public-ok - Stripe webhook needs to be public but validates signature

[functions.generate-otp]
verify_jwt = false
# @public-ok - OTP generation needs to be public for auth flow

[functions.verify-otp]
verify_jwt = false
# @public-ok - OTP verification needs to be public for auth flow

[functions.send-otp-email]
verify_jwt = false
# @public-ok - Email sending needs to be public for auth flow

[functions.healthcare-file-operations]
verify_jwt = true

[functions.test-triggers]
verify_jwt = false
# @public-ok - Testing utility function

[functions.query-performance-monitor]
verify_jwt = true

[functions.error-simulation-test]
verify_jwt = false
# @public-ok - Testing utility function

[functions.backup-restore-manager]
verify_jwt = true

[functions.disaster-recovery-runbook]
verify_jwt = true

[functions.test-audit-triggers]
verify_jwt = false
# @public-ok - Testing utility function

[functions.database-review-tests]
verify_jwt = false
# @public-ok - Testing utility function

[functions.track-referral-signup]
verify_jwt = false
# @public-ok - Public referral tracking

[functions.calculate-advisor-overrides]
verify_jwt = true

[functions.send-payout-notifications]
verify_jwt = true

[functions.partner-onboarding]
verify_jwt = true

[functions.webhook-recording-zoom]
verify_jwt = false
# @public-ok - Zoom webhook needs to be public but validates signature

[functions.webhook-recording-google]
verify_jwt = false
# @public-ok - Google Meet webhook needs to be public but validates signature

[functions.send-recording-notification]
verify_jwt = false
# @public-ok - Email notification service

[functions.send-recording-share-notification]
verify_jwt = false
# @public-ok - Email notification service
