
project_id = "pxmpxujdorfqrxkiaxxw"

# Define SQL migrations to be run
[[migrations]]
file = "20250515_fix_has_role_function.sql"
content = '''
-- Fix the has_role function to properly check user roles
CREATE OR REPLACE FUNCTION public.has_role(user_id uuid, role app_role)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_roles.user_id = has_role.user_id
    AND user_roles.role = has_role.role
  );
$function$
'''
