project_id = "xcmqjkvyvuhoslbzmlgi"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.leads-invite]
verify_jwt = false

[functions.events-track]
verify_jwt = false

[functions.advisors-assign]
verify_jwt = false

[functions.plaid-create-link-token]
verify_jwt = true

[functions.plaid-exchange-public-token]
verify_jwt = true

[functions.plaid-sync-accounts]
verify_jwt = true

[functions.process-transfer]
verify_jwt = false

[functions.stripe-ach-transfer]
verify_jwt = false

[functions.stripe-ach-webhook]
verify_jwt = false

[functions.generate-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.healthcare-file-operations]
verify_jwt = false

[functions.test-triggers]
verify_jwt = false

[functions.query-performance-monitor]
verify_jwt = false

[functions.error-simulation-test]
verify_jwt = false