
project_id = "xcmqjkvyvuhoslbzmlgi"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 900
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.log-security-event]
verify_jwt = true

[functions.export-compliance-report]
verify_jwt = true

[functions.ai-analysis]
verify_jwt = false
# @public-ok - AI analysis can be used publicly

[functions.leads-invite]
verify_jwt = false
# @public-ok - Public invitation system

[functions.events-track]
verify_jwt = false
# @public-ok - Analytics tracking can be public

[functions.advisors-assign]
verify_jwt = true

[functions.plaid-create-link-token]
verify_jwt = true

[functions.plaid-exchange-public-token]
verify_jwt = true

[functions.plaid-sync-accounts]
verify_jwt = true

[functions.process-transfer]
verify_jwt = true

[functions.stripe-ach-transfer]
verify_jwt = true

[functions.stripe-ach-webhook]
verify_jwt = false
# @public-ok - Stripe webhook needs to be public but validates signature

[functions.generate-otp]
verify_jwt = false
# @public-ok - OTP generation needs to be public for auth flow

[functions.verify-otp]
verify_jwt = false
# @public-ok - OTP verification needs to be public for auth flow

[functions.send-otp-email]
verify_jwt = false
# @public-ok - Email sending needs to be public for auth flow

[functions.healthcare-file-operations]
verify_jwt = true

[functions.test-triggers]
verify_jwt = false
# @public-ok - Testing utility function

[functions.query-performance-monitor]
verify_jwt = true

[functions.error-simulation-test]
verify_jwt = false
# @public-ok - Testing utility function

[functions.backup-restore-manager]
verify_jwt = true

[functions.disaster-recovery-runbook]
verify_jwt = true

[functions.test-audit-triggers]
verify_jwt = false
# @public-ok - Testing utility function

[functions.database-review-tests]
verify_jwt = false
# @public-ok - Testing utility function

[functions.track-referral-signup]
verify_jwt = false
# @public-ok - Public referral tracking

[functions.calculate-advisor-overrides]
verify_jwt = true

[functions.send-payout-notifications]
verify_jwt = true

[functions.partner-onboarding]
verify_jwt = true

[functions.webhook-recording-zoom]
verify_jwt = false
# @public-ok - Zoom webhook needs to be public but validates signature

[functions.webhook-recording-google]
verify_jwt = false
# @public-ok - Google Meet webhook needs to be public but validates signature

[functions.send-recording-notification]
verify_jwt = false
# @public-ok - Email notification service

[functions.send-recording-share-notification]
verify_jwt = false

[functions.send-follow-up-email]
verify_jwt = false
# @public-ok - Email notification service

[functions.process-meeting-summary]
verify_jwt = false
# @public-ok - AI processing service for meeting recordings

[functions.send-meeting-summary-email]
verify_jwt = false
# @public-ok - Email notification service for meeting summaries

[functions.parse-retirement-pdf]
verify_jwt = true

[functions.alternative-investments]
verify_jwt = true

[functions.finnhub-stock-stats]
verify_jwt = false
# @public-ok - Market data service

[functions.market-data]
verify_jwt = false
# @public-ok - Market data service

[functions.finnhub-webhook]
verify_jwt = false
# @public-ok - Finnhub webhook endpoint with secret validation

[functions.check-api-keys]
verify_jwt = false
# @public-ok - API key validation utility for QA

[functions.test-api-integrations]
verify_jwt = false
# @public-ok - API integration testing suite for QA

[functions.brand-get]
verify_jwt = false
# @public-ok - Public branding API

[functions.fees-calc]
verify_jwt = false
# @public-ok - Fee calculation with demo mode

[functions.brand-upload-logo]
verify_jwt = true

[functions.process-lead-magnet]
verify_jwt = false
# @public-ok - Lead magnet processing needs to be public

[functions.email-automation]
verify_jwt = false
# @public-ok - Email automation service

[functions.emit-receipt]
verify_jwt = true

[functions.check-approvals]
verify_jwt = true

[functions.issue-pbat]
verify_jwt = true

[functions.ingest-custody-sync]
verify_jwt = false
# @public-ok - Custody data sync service

[functions.reports-render]
verify_jwt = false
# @public-ok - Report generation service

[functions.ipwatch-poll]
verify_jwt = false
# @public-ok - IP monitoring service

[functions.ip-enforcement-verifier]
verify_jwt = false
# @public-ok - Receipt verification service  

[functions.reconcile-enforcement]
verify_jwt = false
# @public-ok - Daily enforcement reconciliation
