
# Pre-commit configuration for secret scanning and security checks
repos:
  - repo: https://github.com/trufflesecurity/trufflehog.git
    rev: main
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["commit", "push"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

  - repo: local
    hooks:
      - id: check-hardcoded-secrets
        name: Check for hardcoded secrets
        entry: bash -c '
          echo "🔍 Scanning for hardcoded secrets...";
          
          # OpenAI API keys
          if git diff --cached --name-only | xargs grep -l "sk-[a-zA-Z0-9]\{48\}" 2>/dev/null; then
            echo "❌ Found potential OpenAI API key!";
            exit 1;
          fi;
          
          # AWS keys  
          if git diff --cached --name-only | xargs grep -l "AKIA[0-9A-Z]\{16\}" 2>/dev/null; then
            echo "❌ Found potential AWS access key!";
            exit 1;
          fi;
          
          # Google API keys
          if git diff --cached --name-only | xargs grep -l "AIza[0-9A-Za-z\\-_]\{35\}" 2>/dev/null; then
            echo "❌ Found potential Google API key!";
            exit 1;
          fi;
          
          # Database connection strings
          if git diff --cached --name-only | xargs grep -l "postgres://.*:.*@" 2>/dev/null; then
            echo "❌ Found potential database connection string!";
            exit 1;
          fi;
          
          echo "✅ No hardcoded secrets detected";
        '
        language: system
        pass_filenames: false
        stages: ["commit"]

      - id: check-unsafe-storage
        name: Check for unsafe secret storage
        entry: bash -c '
          echo "🔍 Checking for unsafe secret storage patterns...";
          
          # localStorage usage with secrets
          if git diff --cached --name-only | xargs grep -l "localStorage.*[Kk]ey\|localStorage.*[Tt]oken\|localStorage.*[Ss]ecret" 2>/dev/null; then
            echo "❌ Found secrets stored in localStorage!";
            exit 1;
          fi;
          
          # sessionStorage usage with secrets  
          if git diff --cached --name-only | xargs grep -l "sessionStorage.*[Kk]ey\|sessionStorage.*[Tt]oken\|sessionStorage.*[Ss]ecret" 2>/dev/null; then
            echo "❌ Found secrets stored in sessionStorage!";
            exit 1;
          fi;
          
          # Direct API calls that should use Edge Functions
          if git diff --cached --name-only | xargs grep -l "fetch.*api\.openai\.com\|fetch.*api\.stripe\.com" 2>/dev/null; then
            echo "⚠️  Found direct API calls - consider using Supabase Edge Functions for security";
          fi;
          
          echo "✅ No unsafe storage patterns detected";
        '
        language: system  
        pass_filenames: false
        stages: ["commit"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
