// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snbuepblwogdkdjjcpek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuYnVlcGJsd29nZGtkampjcGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTc1NDUsImV4cCI6MjA3Mzc5MzU0NX0.IN0Rvdcm18V0mp9M-CDVs1olW3CpEFtvux-i14iUkOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});