
name: API Health Check

on:
  pull_request:
    branches: [ main, master ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  health-check:
    name: API Health Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Newman
        run: npm install -g newman
      
      - name: Run Health Check Tests
        run: |
          newman run ./postman/collections/health-check.json --reporters cli,json --reporter-json-export ./newman-results.json
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: newman-test-results
          path: ./newman-results.json
          
      - name: Check for failures
        if: always()
        run: |
          if grep -q "\"failures\": \[" ./newman-results.json; then
            echo "::error::Health check tests failed. See test results for details."
            exit 1
          fi
