name: Route Audit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  route-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install tsx globally
      run: npm install -g tsx
      
    - name: Run route audit
      run: npm run route:audit
      
    - name: Upload audit results
      uses: actions/upload-artifact@v4
      with:
        name: route-audit-results
        path: out/Route_Audit.csv
        retention-days: 30
        
    - name: Comment on PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = './out/Route_Audit.csv';
          
          if (fs.existsSync(path)) {
            const csvContent = fs.readFileSync(path, 'utf8');
            const lines = csvContent.split('\n');
            const has404Count = lines.filter(line => line.includes('"true"')).length;
            
            const comment = `## 🔍 Route Audit Results
            
            **Total Routes**: ${lines.length - 1}
            **404 Errors**: ${has404Count}
            
            ${has404Count > 0 ? '❌ **FAILURE**: Routes with 404 errors detected' : '✅ **SUCCESS**: No 404 errors found'}
            
            <details>
            <summary>Full Audit Report</summary>
            
            \`\`\`csv
            ${csvContent}
            \`\`\`
            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }